
import React,{useState}from'react';
import{StatusBar}from'expo-status-bar';
import{NavigationContainer,DarkTheme}from'@react-navigation/native';
import{createBottomTabNavigator}from'@react-navigation/bottom-tabs';
import{View,Text,StyleSheet,ScrollView,TouchableOpacity,TextInput}from'react-native';
import{Ionicons}from'@expo/vector-icons';

const Tab=createBottomTabNavigator();
const C={bg:'#120B0B',card:'#1E1414',cream:'#F4EFE7',burg:'#7B0000',red:'#9A1A16',champ:'#C7AD7A',muted:'#B9AFA4'};

function Lobster({size=56}){return <View style={[s.logo,{width:size,height:size}]}><Text style={{fontSize:size*.48}}>🦞</Text></View>}
function Title({eyebrow,title,text}){return <View style={{marginBottom:22}}>{eyebrow?<Text style={s.eye}>{eyebrow}</Text>:null}<Text style={s.h2}>{title}</Text>{text?<Text style={s.body}>{text}</Text>:null}</View>}
function Product({code,name,color,tag}){return <View style={s.product}><View style={[s.swatch,{backgroundColor:color}]}/><View style={{flex:1}}><Text style={s.code}>{code}</Text><Text style={s.pname}>{name}</Text><Text style={s.tag}>{tag}</Text><Text style={s.small}>Premium polarized lenses · UV400</Text></View><Text style={{fontSize:22}}>🦞</Text></View>}

function Home(){return <ScrollView style={s.screen}><View style={s.hero}><Lobster size={80}/><Text style={s.brand}>COAST CLUB</Text><Text style={s.heroTitle}>Built For Life’s Best Moments.</Text><Text style={s.heroText}>L’app interactive Coast Club : souvenirs, map, passport, collections et drops.</Text></View><View style={s.pad}><Title eyebrow="TODAY" title="The best moments are never planned." text="Ajoute un moment, un lieu, des personnes, une photo, puis transforme-le en Memory Card."/><View style={s.quote}><Text style={s.quoteText}>“The lobster is what people recognize. Built For Life’s Best Moments is what people remember.”</Text></View><Product code="CHC001" name="Sunset Bourgogne" color="#6A0909" tag="The First Icon"/></View></ScrollView>}

function Passport(){const[moments]=useState([{t:'Golden hour with the boys',p:'Biarritz',d:'18 Jun 2026',m:'Nobody wanted to leave.'},{t:'No destination',p:'Coastal road',d:'Summer 2026',m:'Windows down, music loud.'}]);return <ScrollView style={s.screen}><View style={s.pad}><Title eyebrow="PASSPORT" title="Your best moments." text="Pas une carte des pays visités. Une archive des moments vécus."/><View style={s.form}><Text style={s.label}>Add a memory</Text><TextInput placeholder="Moment title" placeholderTextColor="#7F7470" style={s.input}/><TextInput placeholder="Location" placeholderTextColor="#7F7470" style={s.input}/><TouchableOpacity style={s.button}><Text style={s.buttonText}>Create Memory Card</Text></TouchableOpacity></View>{moments.map((x,i)=><View key={i} style={s.memory}><Text style={s.code}>MEMORY 00{i+1}</Text><Text style={s.memTitle}>{x.t}</Text><Text style={s.meta}>{x.p} · {x.d}</Text><Text style={s.body}>{x.m}</Text></View>)}</View></ScrollView>}

function Map(){let places=['Kiribati','Bali','Bocas','Panama','Costa Rica','Nicaragua','Açores','Corsica'];return <ScrollView style={s.screen}><View style={s.pad}><Title eyebrow="MAP" title="Places that feel like Coast Club." text="Une carte mentale du kiff : pas les endroits les plus connus, les endroits qui donnent envie de vivre quelque chose."/><View style={s.map}><Text style={s.mapSmall}>PACIFIC · CENTRAL AMERICA · ISLANDS</Text><Text style={s.mapBig}>COAST CLUB MAP</Text></View><View style={s.chips}>{places.map(p=><View key={p} style={s.chip}><Text style={s.chipText}>{p}</Text></View>)}</View></View></ScrollView>}

function Collections(){let products=[['CHC001','Sunset Bourgogne','#6A0909','The First Icon'],['CC001','Dock Club','#5B3A27','Coast Collection'],['CCS004','Sun Club','#FFD21A','Be Stoked'],['CCP001','Kiribati','#E8DCC8','Pacific Series'],['CHL001','Lobster Club','#050505','20 pieces only']];return <ScrollView style={s.screen}><View style={s.pad}><Title eyebrow="LOOKBOOK" title="Collections." text="CC · CCS · CHC · CHL · CCP"/>{products.map(p=><Product key={p[0]} code={p[0]} name={p[1]} color={p[2]} tag={p[3]}/>)}</View></ScrollView>}

function Journal(){let a=[['Why the lobster matters','The symbol comes first. The meaning follows.'],['CCP — Pacific','Kiribati, Bali and Bocas are the first territories explored.'],['The First Icon','CHC001 Sunset Bourgogne is the pair that started it all.']];return <ScrollView style={s.screen}><View style={s.pad}><Title eyebrow="JOURNAL" title="Stories, drops and notes."/>{a.map((x,i)=><View key={i} style={s.article}><Text style={s.code}>ARTICLE 00{i+1}</Text><Text style={s.articleTitle}>{x[0]}</Text><Text style={s.body}>{x[1]}</Text></View>)}</View></ScrollView>}

function Tabs(){return <Tab.Navigator screenOptions={({route})=>({headerStyle:{backgroundColor:C.bg},headerTintColor:C.cream,tabBarStyle:{backgroundColor:'#100808',borderTopColor:'#2C1B1B'},tabBarActiveTintColor:C.champ,tabBarInactiveTintColor:'#847A75',tabBarIcon:({color,size})=>{let icons={Home:'home',Passport:'book',Map:'map',Collections:'glasses',Journal:'newspaper'};return <Ionicons name={icons[route.name]} size={size} color={color}/>}})}><Tab.Screen name="Home" component={Home}/><Tab.Screen name="Passport" component={Passport}/><Tab.Screen name="Map" component={Map}/><Tab.Screen name="Collections" component={Collections}/><Tab.Screen name="Journal" component={Journal}/></Tab.Navigator>}

export default function App(){return <NavigationContainer theme={{...DarkTheme,colors:{...DarkTheme.colors,background:C.bg}}}><Tabs/><StatusBar style="light"/></NavigationContainer>}

const s=StyleSheet.create({screen:{flex:1,backgroundColor:C.bg},pad:{padding:20,paddingBottom:36},hero:{minHeight:520,alignItems:'center',justifyContent:'center',padding:26,backgroundColor:'#210D0D'},logo:{borderRadius:18,backgroundColor:C.cream,alignItems:'center',justifyContent:'center',marginBottom:20},brand:{color:C.cream,letterSpacing:8,fontSize:18,marginBottom:20,fontWeight:'700'},heroTitle:{color:C.cream,fontSize:48,lineHeight:50,fontFamily:'Georgia',textAlign:'center'},heroText:{color:C.muted,textAlign:'center',fontSize:16,lineHeight:24,marginTop:20,maxWidth:330},eye:{color:C.champ,fontSize:12,letterSpacing:3,fontWeight:'800',marginBottom:10},h2:{color:C.cream,fontSize:34,lineHeight:38,fontFamily:'Georgia',marginBottom:12},body:{color:C.muted,fontSize:15,lineHeight:22},quote:{backgroundColor:C.card,borderWidth:1,borderColor:'#3A2525',padding:22,borderRadius:24,marginBottom:30},quoteText:{color:C.cream,fontSize:23,lineHeight:30,fontFamily:'Georgia'},product:{flexDirection:'row',alignItems:'center',gap:16,backgroundColor:C.card,borderRadius:24,padding:16,marginBottom:14,borderWidth:1,borderColor:'#302020'},swatch:{width:74,height:74,borderRadius:20,borderWidth:1,borderColor:'rgba(255,255,255,.14)'},code:{color:C.champ,letterSpacing:2,fontSize:11,fontWeight:'800'},pname:{color:C.cream,fontSize:22,fontFamily:'Georgia',marginTop:4},tag:{color:C.red,fontWeight:'700',marginTop:4},small:{color:C.muted,fontSize:13,marginTop:4},form:{backgroundColor:C.card,borderRadius:24,padding:18,marginBottom:20,borderWidth:1,borderColor:'#302020'},label:{color:C.cream,fontWeight:'800',marginBottom:12},input:{backgroundColor:'#120B0B',color:C.cream,borderRadius:14,padding:14,marginBottom:10,borderWidth:1,borderColor:'#312020'},button:{backgroundColor:C.burg,padding:15,borderRadius:14,alignItems:'center'},buttonText:{color:C.cream,fontWeight:'800',letterSpacing:1},memory:{backgroundColor:'#171010',padding:20,borderRadius:24,marginBottom:14,borderWidth:1,borderColor:'#302020'},memTitle:{color:C.cream,fontSize:25,fontFamily:'Georgia',marginBottom:4},meta:{color:C.red,fontWeight:'700',marginBottom:10},map:{height:260,backgroundColor:C.cream,borderRadius:28,justifyContent:'center',alignItems:'center',padding:24,marginBottom:20},mapSmall:{color:C.burg,letterSpacing:2,fontSize:11,textAlign:'center',fontWeight:'800'},mapBig:{color:C.burg,fontSize:36,lineHeight:40,fontFamily:'Georgia',marginTop:14,textAlign:'center'},chips:{flexDirection:'row',flexWrap:'wrap',gap:10},chip:{paddingVertical:10,paddingHorizontal:14,borderRadius:100,backgroundColor:C.card,borderWidth:1,borderColor:'#302020'},chipText:{color:C.cream},article:{padding:20,borderRadius:24,backgroundColor:C.card,marginBottom:14,borderWidth:1,borderColor:'#302020'},articleTitle:{color:C.cream,fontSize:25,fontFamily:'Georgia',marginBottom:8}});
